### ISSUE TITLE
Heatmap REST

### ISSUE THREAD

**Issue by muellerjonas** [we-loview/loview-backend#26]
Return a list of S2 and number of users for each rectangle.
FE also needs the coordinates of the S2 rectangles

**Comment by muellerjonas** [comment]
@Christoph-Maximilian This also got higher priority because it's explicitly included in the project scope and Mr. Frontend is waiting for it

**Comment by Christoph-Maximilian** [comment]
I need more info about this -> what data do you want and what is the logic behind this?

**Comment by muellerjonas** [comment]
As far as I remember the idea was that we split the current viewport in e.g. 1000 equally sizes squares and return the coordinates for these squares along with how many users have their latest location in the respective squares to the frontend. 
Right Felix?
Like this the frontend is able to display Heatmaps
