### ISSUE TITLE
REST-Endpoint for user lookup

### ISSUE THREAD

**Issue by FelixSchwarzmeier** [we-loview/loview-backend#61]
REST Response: [{
  user_id: "...",
  lat: 00.00,
  lng: 00.00,
  age: 00,
  picture: "...",
  name: "",
  gender: 0,
  homeLocation: "..."
}]

👆REST BITTE!

**Comment by muellerjonas** [comment]
homeLocation is called "locations-home-city"
Additionally: "server_status" field that returns a status according to server_status.py: 200, 521 or 522
