### ISSUE TITLE
Check if GeoService is messed up somewhere

### ISSUE THREAD

**Issue by muellerjonas** [we-loview/loview-backend#64]
Since we're getting so many locations for this one area around Marsstraße, e.g. 30k for a little square when using all locations (see Felix' Slack messages on Jan 29th at ~10PM)

**Comment by Christoph-Maximilian** [comment]
It is not the problem of the geoserver -> many users dont allow lovoo access their gps location -> they have a standard location (and this default location for munich is near Marsstraße)
